apiVersion: v1
kind: Service
metadata:
  name: {{ include "cng-hello-backend.fullname" . }}
  labels:
    {{ - include "cng-hello-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ - include "cng-hello-backend.selectorLabels" . | nindent 4 }}
