
networks:
  web:
  internal:

services:

  cng-hello-backend:
    image: cng-hello-backend:latest
    ports:
      - "8080:8080"
    environment:
      SERVICE_NAME: "cng-hello-backend"
      PORT: "8080"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "cngdb"
      LOG_LEVEL: "DEBUG"
    networks:
      - web
      - internal
    depends_on:
      - prometheus
      - jaeger
      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cngdb
    networks:
      - internal

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - web
      - internal

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - web
      - internal

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14250:14250" # Collector gRPC
      - "16686:16686" # Web HTTP
    networks:
      - web
      - internal
  
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
        - "4317:4317" # OTLP over gRPC receiver
        - "9464:9464" # Prometheus 
        - "8888:8888"   # Prometheus metrics exposed by the collector
        - "8889:8889"   # Prometheus exporter metrics
    networks:
      - internal
    depends_on:
        - jaeger
        - prometheus

volumes:
  grafana-data: