networks:
  web:
  internal:

services:

  cng-hello-backend:
    image: cng-hello-backend:latest
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "cngdb"
      LOG_LEVEL: "DEBUG"
    networks:
      - web
      - internal
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cngdb
    networks:
      - internal