extensions:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317 # It is important that we do not use localhost

processors:
  memory_limiter:
    limit_percentage: 75
    check_interval: 5s
    spike_limit_percentage: 30
  batch:
    send_batch_size: 8192

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  # otlp/jaeger:
  #   endpoint: jaeger:14250
  #   tls:
  #     insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
  # azuremonitor:
  #   instrumentation_key: 


service:
  # A pipeline consists of a set of receivers, processors and exporters.
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

