# Doc: https://prometheus.io/docs/prometheus/latest/configuration/configuration/
global:
  scrape_interval:     10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  - job_name: 'loki'
    static_configs:
      - targets: [ 'loki:3100' ]
  - job_name: 'grafana'
    static_configs:
      - targets: [ 'grafana:3000' ]