# Doc: https://grafana.com/docs/tempo/latest/configuration/
server:
  http_listen_port: 3200
  log_level: warn

distributor:
  receivers:                          
    otlp:
      protocols:
        grpc:

ingester:
  max_block_duration: 5m               # cut the headblock when this much time passes. this is being set for demo purposes and should probably be left alone normally

compactor:
  compaction:
    block_retention: 1h                # overall Tempo trace retention. set for demo purposes

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write

storage:
  trace:
    backend: s3                     # backend configuration to use
    wal:
      path: /tmp/tempo/wal             # where to store the the wal locally
    s3:
      bucket: tempo-data
      endpoint: minio:9000
      access_key: minio
      secret_key: supersecret
      insecure: true
      forcepathstyle: true

overrides:
  metrics_generator_processors: [service-graphs, span-metrics] # enables metrics generator